### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by NadineAziz** [NadineAziz/gpu-homework#2]
- [ ] Implement the space-partitioned version of the N-body simulation seen in the practice, that is, divide the simulation space into smaller blocks within which the interaction (with particles of the nearest neighboring blocks) is exact, but distant blocks interact only through their centers of mass. (40%)

- [x] changing the gravitational constant, (5%)
- [x] setting the number of objects, (5%)
- [x] changing the type of initial distribution of the objects (e.g., uniform/non-uniform randomization). (10%)

- [x] Implement the N-body simulation in 3D (10%)
- [x] user can navigate space and observe the simulation from different viewpoints (20%)
